#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/terry/.vscode-server/bin/bf9252a2fb45be6893dd8870c0bf37e2e1766d61/node" "/home/terry/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/copilotCLIShim.js" "$@"